name: Build and publish image to docker-hub

# Trigger: set to trigger on a push, this can be changed to a release also if we want to 
# publish the image everytime a new release of the app is created
on:
  push:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    # Check out the repo code
      - name: Check out the repo
        uses: actions/checkout@v4
    # Set up docker to build the app
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to docker - Commenting out the docker login step.
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   # The following secrets are to be stored as a repo secret in the repository
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      #  Build the docker image - dummy hub namespace - for tagging i'm using the github commit sha
      - name: Build Docker image
        run: |
          docker build -t my-docker-hub-namespace/interview-dotnet-app:${{ github.sha }} -t my-docker-hub-namespace/interview-dotnet-app:latest .
          
      # Final step is to push the image to docker hub, this is commented out also and the docker image at the push is again tagged with the github sha
      # - name: Push Docker image to Docker Hub
      #   run: |
      #     docker push my-docker-hub-namespace/interview-dotnet-app:${{ github.sha }}
      #     docker push my-docker-hub-namespace/interview-dotnet-app:latest

